### ISSUE TITLE
Error when restore .Net Core 3.0 Console application via VS 

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/test-templates#27]
### Steps to reproduce
Create a new .net core console application via VS,
Restore
### Expected behavior
Restore succeeded with no warnings and no errors.
### Actual behavior
```
Error	MSB4018	The "CreateAppHost" task failed unexpectedly.
Microsoft.NET.Build.Tasks.ResourceUpdater+HResultException: 80070002
   at Microsoft.NET.Build.Tasks.ResourceUpdater.AddResourcesFromPEImage(String peFile)
   at Microsoft.NET.Build.Tasks.AppHost.Create(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String intermediateAssembly, Logger log)
   at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```	
![3 0](https://user-images.githubusercontent.com/33921754/47353526-1012de80-d6ef-11e8-81d8-ae23e5971974.PNG)

Note: When I manually change the target fx to 2.1, it shows the same error. 
### Environment data
CLI/SDK - 3.0.100-alpha1-009697 against d16.0stg
dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009697
 Commit:    7365786612

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\

Host (useful for support):
  Version: 3.0.0-preview1-27018-05
  Commit:  7a7ca06512

.NET Core SDKs installed:
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009431 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009697 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35364 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35364 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27017-4 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27001-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-27018-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by richaverma1** [comment]
Fixed via https://github.com/dotnet/sdk/pull/2604 . The issue can be closed. I don't have permissions to close this issue.
